// Package manpage renders section-8 man pages for the briefs-utils
// commands via urfave/cli-docs.  It is invoked by the hidden
// --generate-man-page flag on mkfs.briefs, fsck.briefs, and fuse.briefs,
// which write man/man8/<name>.8 when run from the repository root.
package manpage

import (
	"fmt"
	"os"
	"path/filepath"

	docs "github.com/urfave/cli-docs/v3"
	"github.com/urfave/cli/v3"
)

// Generate renders a section-8 man page for cmd (titled after cmd.Name)
// using urfave/cli-docs and writes it to dir/<cmd.Name>.8.  The directory
// is created if it does not exist.  A leading ".\" generated, do not edit"
// comment is prepended so the file is recognisable as generated.  It
// returns the path written.
func Generate(cmd *cli.Command, dir string) (string, error) {
	man, err := docs.ToManWithSection(cmd, 8)
	if err != nil {
		return "", fmt.Errorf("render man page: %w", err)
	}

	header := ".\" Generated by `make man` (urfave/cli-docs ToManWithSection); do not edit by hand.\n" +
		".\" Regenerate with: " + cmd.Name + " --generate-man-page\n\n"

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create %s: %w", dir, err)
	}

	path := filepath.Join(dir, cmd.Name+".8")
	if err := os.WriteFile(path, append([]byte(header), []byte(man)...), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", path, err)
	}
	return path, nil
}
