// Code generated by cmd/gendisk. DO NOT EDIT.

package briefs

import (
	"encoding/binary"
	"fmt"
	"unsafe"
)

// Size returns the on-disk size of Inode.
func (s *Inode) Size() int { return int(unsafe.Sizeof(Inode{})) }

// MarshalBinary serializes Inode to its little-endian on-disk representation.
func (s *Inode) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.InodeNumber); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Magic); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.Filemode); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Uid); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Gid); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s._Pad0); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.FileSize); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.CtimeSec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.CtimeNsec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.AtimeSec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.AtimeNsec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.MtimeSec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.MtimeNsec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.CreationTimeSec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.CreationTimeNsec); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.Nlinks); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.NumExtentsInline); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.ExtentInlineBase); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.NumExtentsTotal); pos += 8
	copy(data[pos:], s.inlineRegion[:]); pos += 256
	binary.LittleEndian.PutUint64(data[pos:], s.XattrOffset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.XattrSize); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.ParentInode); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.Unused); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Flags); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.DirTrieRoot); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Rdev); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Generation); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.UserFlags); pos += 4
	copy(data[pos:], s.Reserved[:]); pos += 68
	return data, nil
}

// UnmarshalBinary deserializes Inode from its little-endian on-disk representation.
func (s *Inode) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("Inode data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.InodeNumber = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Magic = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Filemode = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Uid = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Gid = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s._Pad0 = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.FileSize = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.CtimeSec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.CtimeNsec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.AtimeSec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.AtimeNsec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.MtimeSec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.MtimeNsec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.CreationTimeSec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.CreationTimeNsec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Nlinks = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.NumExtentsInline = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.ExtentInlineBase = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.NumExtentsTotal = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	copy(s.inlineRegion[:], data[pos:pos+256]); pos += 256
	s.XattrOffset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.XattrSize = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.ParentInode = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Unused = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Flags = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.DirTrieRoot = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Rdev = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Generation = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.UserFlags = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	copy(s.Reserved[:], data[pos:pos+68]); pos += 68
	return nil
}

// Compile-time size assertion for Inode.
var _ = [1]struct{}{}[unsafe.Sizeof(Inode{}) - 512]

// Size returns the on-disk size of SuperblockLayout.
func (s *SuperblockLayout) Size() int { return int(unsafe.Sizeof(SuperblockLayout{})) }

// MarshalBinary serializes SuperblockLayout to its little-endian on-disk representation.
func (s *SuperblockLayout) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Magic); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.MajorVer); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.MinorVer); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.PatchVer); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.TotalBlocks); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.DataBlocks); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.BlockSize); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.InodeSize); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.BlocksGrp); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.InodesGrp); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FSCreated); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FSLastMount); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FSLastChkpt); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FreeDataBlks); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FreeInodes); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.RootIno); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FeatCompat); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FeatROCompat); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FeatIncompat); pos += 8
	copy(data[pos:], s.UUID[:]); pos += 16
	binary.LittleEndian.PutUint64(data[pos:], s.EATOffset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.EATBlocks); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.TrieRootBlock); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.TrieBlocksUsed); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.TrieNodePoolStart); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.TrieNodePoolSize); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.InodeBMOffset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.InodeBMBlocks); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.InodeTableOffset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.JournalOffset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.JournalBlocks); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.CheckpointSeq); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.JournalLogStart); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.JournalLogEnd); pos += 8
	for i := 0; i < len(s.ReservedJournal); i++ {
		binary.LittleEndian.PutUint64(data[pos:], s.ReservedJournal[i]); pos += 8
	}
	copy(data[pos:], s.Label[:]); pos += 64
	copy(data[pos:], s.Reserved[:]); pos += 648
	return data, nil
}

// UnmarshalBinary deserializes SuperblockLayout from its little-endian on-disk representation.
func (s *SuperblockLayout) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("SuperblockLayout data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Magic = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.MajorVer = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.MinorVer = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.PatchVer = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.TotalBlocks = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.DataBlocks = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.BlockSize = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.InodeSize = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.BlocksGrp = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.InodesGrp = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FSCreated = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FSLastMount = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FSLastChkpt = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FreeDataBlks = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FreeInodes = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.RootIno = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FeatCompat = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FeatROCompat = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FeatIncompat = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	copy(s.UUID[:], data[pos:pos+16]); pos += 16
	s.EATOffset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.EATBlocks = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.TrieRootBlock = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.TrieBlocksUsed = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.TrieNodePoolStart = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.TrieNodePoolSize = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.InodeBMOffset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.InodeBMBlocks = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.InodeTableOffset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.JournalOffset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.JournalBlocks = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.CheckpointSeq = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.JournalLogStart = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.JournalLogEnd = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	for i := 0; i < len(s.ReservedJournal); i++ {
		s.ReservedJournal[i] = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	}
	copy(s.Label[:], data[pos:pos+64]); pos += 64
	copy(s.Reserved[:], data[pos:pos+648]); pos += 648
	return nil
}

// Compile-time size assertion for SuperblockLayout.
var _ = [1]struct{}{}[unsafe.Sizeof(SuperblockLayout{}) - 1024]

