// Code generated by cmd/gendisk. DO NOT EDIT.

package briefs

import (
	"encoding/binary"
	"fmt"
	"unsafe"
)

// Size returns the on-disk size of AllocHeader.
func (s *AllocHeader) Size() int { return int(unsafe.Sizeof(AllocHeader{})) }

// MarshalBinary serializes AllocHeader to its little-endian on-disk representation.
func (s *AllocHeader) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint32(data[pos:], s.Magic); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Version); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.L0Words); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.L1Words); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.L2Words); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.BlockCount); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FreeCount); pos += 8
	return data, nil
}

// UnmarshalBinary deserializes AllocHeader from its little-endian on-disk representation.
func (s *AllocHeader) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("AllocHeader data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Magic = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Version = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.L0Words = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.L1Words = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.L2Words = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.BlockCount = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FreeCount = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	return nil
}

// Compile-time size assertion for AllocHeader.
var _ = [1]struct{}{}[unsafe.Sizeof(AllocHeader{}) - 48]

// Size returns the on-disk size of BtreeIdxEntry.
func (s *BtreeIdxEntry) Size() int { return int(unsafe.Sizeof(BtreeIdxEntry{})) }

// MarshalBinary serializes BtreeIdxEntry to its little-endian on-disk representation.
func (s *BtreeIdxEntry) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Child); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.HighKey); pos += 8
	return data, nil
}

// UnmarshalBinary deserializes BtreeIdxEntry from its little-endian on-disk representation.
func (s *BtreeIdxEntry) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("BtreeIdxEntry data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Child = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.HighKey = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	return nil
}

// Compile-time size assertion for BtreeIdxEntry.
var _ = [1]struct{}{}[unsafe.Sizeof(BtreeIdxEntry{}) - 16]

// Size returns the on-disk size of BtreeNodeHeader.
func (s *BtreeNodeHeader) Size() int { return int(unsafe.Sizeof(BtreeNodeHeader{})) }

// MarshalBinary serializes BtreeNodeHeader to its little-endian on-disk representation.
func (s *BtreeNodeHeader) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint32(data[pos:], s.Magic); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Flags); pos += 4
	binary.LittleEndian.PutUint16(data[pos:], s.Level); pos += 2
	binary.LittleEndian.PutUint16(data[pos:], s.NumKeys); pos += 2
	binary.LittleEndian.PutUint32(data[pos:], s._Pad); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.NextLeaf); pos += 8
	return data, nil
}

// UnmarshalBinary deserializes BtreeNodeHeader from its little-endian on-disk representation.
func (s *BtreeNodeHeader) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("BtreeNodeHeader data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Magic = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Flags = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Level = binary.LittleEndian.Uint16(data[pos:]); pos += 2
	s.NumKeys = binary.LittleEndian.Uint16(data[pos:]); pos += 2
	s._Pad = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.NextLeaf = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	return nil
}

// Compile-time size assertion for BtreeNodeHeader.
var _ = [1]struct{}{}[unsafe.Sizeof(BtreeNodeHeader{}) - 24]

// Size returns the on-disk size of Checkpoint.
func (s *Checkpoint) Size() int { return int(unsafe.Sizeof(Checkpoint{})) }

// MarshalBinary serializes Checkpoint to its little-endian on-disk representation.
func (s *Checkpoint) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Seq); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.RecordCount); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Reserved1); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.LogSequenceEnd); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.TrieRootNode); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FreeDataCount); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FreeInodeCount); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Reserved2); pos += 8
	return data, nil
}

// UnmarshalBinary deserializes Checkpoint from its little-endian on-disk representation.
func (s *Checkpoint) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("Checkpoint data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Seq = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.RecordCount = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Reserved1 = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.LogSequenceEnd = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.TrieRootNode = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FreeDataCount = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FreeInodeCount = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Reserved2 = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	return nil
}

// Compile-time size assertion for Checkpoint.
var _ = [1]struct{}{}[unsafe.Sizeof(Checkpoint{}) - 56]

// Size returns the on-disk size of Extent.
func (s *Extent) Size() int { return int(unsafe.Sizeof(Extent{})) }

// MarshalBinary serializes Extent to its little-endian on-disk representation.
func (s *Extent) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Offset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Phys); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Len); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.Flags); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Pad); pos += 4
	return data, nil
}

// UnmarshalBinary deserializes Extent from its little-endian on-disk representation.
func (s *Extent) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("Extent data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Offset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Phys = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Len = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Flags = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Pad = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	return nil
}

// Compile-time size assertion for Extent.
var _ = [1]struct{}{}[unsafe.Sizeof(Extent{}) - 32]

// Size returns the on-disk size of Inode.
func (s *Inode) Size() int { return int(unsafe.Sizeof(Inode{})) }

// MarshalBinary serializes Inode to its little-endian on-disk representation.
func (s *Inode) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.InodeNumber); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Magic); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.Filemode); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Uid); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Gid); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s._Pad0); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.FileSize); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.CtimeSec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.CtimeNsec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.AtimeSec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.AtimeNsec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.MtimeSec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.MtimeNsec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.CreationTimeSec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.CreationTimeNsec); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.Nlinks); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.NumExtentsInline); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.ExtentInlineBase); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.NumExtentsTotal); pos += 8
	copy(data[pos:], s.inlineRegion[:]); pos += 256
	binary.LittleEndian.PutUint64(data[pos:], s.XattrOffset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.XattrSize); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.ParentInode); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.Unused); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Flags); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.DirTrieRoot); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Rdev); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Generation); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.UserFlags); pos += 4
	copy(data[pos:], s.Reserved[:]); pos += 68
	return data, nil
}

// UnmarshalBinary deserializes Inode from its little-endian on-disk representation.
func (s *Inode) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("Inode data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.InodeNumber = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Magic = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Filemode = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Uid = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Gid = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s._Pad0 = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.FileSize = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.CtimeSec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.CtimeNsec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.AtimeSec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.AtimeNsec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.MtimeSec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.MtimeNsec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.CreationTimeSec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.CreationTimeNsec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Nlinks = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.NumExtentsInline = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.ExtentInlineBase = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.NumExtentsTotal = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	copy(s.inlineRegion[:], data[pos:pos+256]); pos += 256
	s.XattrOffset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.XattrSize = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.ParentInode = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Unused = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Flags = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.DirTrieRoot = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Rdev = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Generation = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.UserFlags = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	copy(s.Reserved[:], data[pos:pos+68]); pos += 68
	return nil
}

// Compile-time size assertion for Inode.
var _ = [1]struct{}{}[unsafe.Sizeof(Inode{}) - 512]

// Size returns the on-disk size of JournalBlockHeader.
func (s *JournalBlockHeader) Size() int { return int(unsafe.Sizeof(JournalBlockHeader{})) }

// MarshalBinary serializes JournalBlockHeader to its little-endian on-disk representation.
func (s *JournalBlockHeader) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint32(data[pos:], s.Magic); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.BlockSeq); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.RecordCount); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Reserved); pos += 4
	return data, nil
}

// UnmarshalBinary deserializes JournalBlockHeader from its little-endian on-disk representation.
func (s *JournalBlockHeader) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("JournalBlockHeader data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Magic = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.BlockSeq = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.RecordCount = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Reserved = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	return nil
}

// Compile-time size assertion for JournalBlockHeader.
var _ = [1]struct{}{}[unsafe.Sizeof(JournalBlockHeader{}) - 16]

// Size returns the on-disk size of JrnDirUpdate.
func (s *JrnDirUpdate) Size() int { return int(unsafe.Sizeof(JrnDirUpdate{})) }

// MarshalBinary serializes JrnDirUpdate to its little-endian on-disk representation.
func (s *JrnDirUpdate) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.ParentIno); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.ChildIno); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.NameLen); pos += 4
	copy(data[pos:], s.Name[:]); pos += 255
	data[pos] = s.Op; pos += 1
	data[pos] = s.FType; pos += 1
	copy(data[pos:], s.Reserved[:]); pos += 1
	copy(data[pos:], s._Pad[:]); pos += 2
	return data, nil
}

// UnmarshalBinary deserializes JrnDirUpdate from its little-endian on-disk representation.
func (s *JrnDirUpdate) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("JrnDirUpdate data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.ParentIno = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.ChildIno = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.NameLen = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	copy(s.Name[:], data[pos:pos+255]); pos += 255
	s.Op = data[pos]; pos += 1
	s.FType = data[pos]; pos += 1
	copy(s.Reserved[:], data[pos:pos+1]); pos += 1
	copy(s._Pad[:], data[pos:pos+2]); pos += 2
	return nil
}

// Compile-time size assertion for JrnDirUpdate.
var _ = [1]struct{}{}[unsafe.Sizeof(JrnDirUpdate{}) - 280]

// Size returns the on-disk size of JrnExtentAlloc.
func (s *JrnExtentAlloc) Size() int { return int(unsafe.Sizeof(JrnExtentAlloc{})) }

// MarshalBinary serializes JrnExtentAlloc to its little-endian on-disk representation.
func (s *JrnExtentAlloc) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Ino); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Offset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Length); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.PhysStart); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.ExtentIndex); pos += 4
	copy(data[pos:], s.Reserved[:]); pos += 44
	return data, nil
}

// UnmarshalBinary deserializes JrnExtentAlloc from its little-endian on-disk representation.
func (s *JrnExtentAlloc) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("JrnExtentAlloc data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Ino = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Offset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Length = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.PhysStart = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.ExtentIndex = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	copy(s.Reserved[:], data[pos:pos+44]); pos += 44
	return nil
}

// Compile-time size assertion for JrnExtentAlloc.
var _ = [1]struct{}{}[unsafe.Sizeof(JrnExtentAlloc{}) - 80]

// Size returns the on-disk size of JrnExtentFree.
func (s *JrnExtentFree) Size() int { return int(unsafe.Sizeof(JrnExtentFree{})) }

// MarshalBinary serializes JrnExtentFree to its little-endian on-disk representation.
func (s *JrnExtentFree) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Ino); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Offset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.PhysStart); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Length); pos += 8
	copy(data[pos:], s.Reserved[:]); pos += 48
	return data, nil
}

// UnmarshalBinary deserializes JrnExtentFree from its little-endian on-disk representation.
func (s *JrnExtentFree) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("JrnExtentFree data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Ino = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Offset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.PhysStart = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Length = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	copy(s.Reserved[:], data[pos:pos+48]); pos += 48
	return nil
}

// Compile-time size assertion for JrnExtentFree.
var _ = [1]struct{}{}[unsafe.Sizeof(JrnExtentFree{}) - 80]

// Size returns the on-disk size of JrnInodeAlloc.
func (s *JrnInodeAlloc) Size() int { return int(unsafe.Sizeof(JrnInodeAlloc{})) }

// MarshalBinary serializes JrnInodeAlloc to its little-endian on-disk representation.
func (s *JrnInodeAlloc) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Ino); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.Mode); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Nlink); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Uid); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Gid); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Reserved1); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s._Pad); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.Reserved2); pos += 8
	return data, nil
}

// UnmarshalBinary deserializes JrnInodeAlloc from its little-endian on-disk representation.
func (s *JrnInodeAlloc) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("JrnInodeAlloc data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Ino = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Mode = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Nlink = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Uid = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Gid = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Reserved1 = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s._Pad = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Reserved2 = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	return nil
}

// Compile-time size assertion for JrnInodeAlloc.
var _ = [1]struct{}{}[unsafe.Sizeof(JrnInodeAlloc{}) - 40]

// Size returns the on-disk size of JrnInodeFree.
func (s *JrnInodeFree) Size() int { return int(unsafe.Sizeof(JrnInodeFree{})) }

// MarshalBinary serializes JrnInodeFree to its little-endian on-disk representation.
func (s *JrnInodeFree) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Ino); pos += 8
	for i := 0; i < len(s.Reserved); i++ {
		binary.LittleEndian.PutUint32(data[pos:], s.Reserved[i]); pos += 4
	}
	binary.LittleEndian.PutUint32(data[pos:], s._Pad); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.Reserved2); pos += 8
	return data, nil
}

// UnmarshalBinary deserializes JrnInodeFree from its little-endian on-disk representation.
func (s *JrnInodeFree) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("JrnInodeFree data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Ino = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	for i := 0; i < len(s.Reserved); i++ {
		s.Reserved[i] = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	}
	s._Pad = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Reserved2 = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	return nil
}

// Compile-time size assertion for JrnInodeFree.
var _ = [1]struct{}{}[unsafe.Sizeof(JrnInodeFree{}) - 32]

// Size returns the on-disk size of JrnInodeFull.
func (s *JrnInodeFull) Size() int { return int(unsafe.Sizeof(JrnInodeFull{})) }

// MarshalBinary serializes JrnInodeFull to its little-endian on-disk representation.
func (s *JrnInodeFull) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Ino); pos += 8
	copy(data[pos:], s.InodeData[:]); pos += 512
	copy(data[pos:], s.Reserved[:]); pos += 40
	return data, nil
}

// UnmarshalBinary deserializes JrnInodeFull from its little-endian on-disk representation.
func (s *JrnInodeFull) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("JrnInodeFull data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Ino = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	copy(s.InodeData[:], data[pos:pos+512]); pos += 512
	copy(s.Reserved[:], data[pos:pos+40]); pos += 40
	return nil
}

// Compile-time size assertion for JrnInodeFull.
var _ = [1]struct{}{}[unsafe.Sizeof(JrnInodeFull{}) - 560]

// Size returns the on-disk size of JrnInodeUpdate.
func (s *JrnInodeUpdate) Size() int { return int(unsafe.Sizeof(JrnInodeUpdate{})) }

// MarshalBinary serializes JrnInodeUpdate to its little-endian on-disk representation.
func (s *JrnInodeUpdate) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Ino); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.Mode); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Nlink); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Uid); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Gid); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.FileSize); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.ATimeSec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.ATimeNsec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.MTimeSec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.MTimeNsec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.CTimeSec); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.CTimeNsec); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.Flags); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Reserved); pos += 4
	return data, nil
}

// UnmarshalBinary deserializes JrnInodeUpdate from its little-endian on-disk representation.
func (s *JrnInodeUpdate) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("JrnInodeUpdate data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Ino = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Mode = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Nlink = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Uid = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Gid = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.FileSize = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.ATimeSec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.ATimeNsec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.MTimeSec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.MTimeNsec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.CTimeSec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.CTimeNsec = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Flags = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Reserved = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	return nil
}

// Compile-time size assertion for JrnInodeUpdate.
var _ = [1]struct{}{}[unsafe.Sizeof(JrnInodeUpdate{}) - 88]

// Size returns the on-disk size of JrnSymlinkPrefix. Packed structs have
// unaligned on-disk fields that Go's struct alignment cannot represent, so
// this is the declared size, not unsafe.Sizeof (the field-width sum is
// verified at generation time).
func (s *JrnSymlinkPrefix) Size() int { return 20 }

// MarshalBinary serializes JrnSymlinkPrefix to its little-endian on-disk representation.
func (s *JrnSymlinkPrefix) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Ino); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Phys); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.TargetLen); pos += 4
	return data, nil
}

// UnmarshalBinary deserializes JrnSymlinkPrefix from its little-endian on-disk representation.
func (s *JrnSymlinkPrefix) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("JrnSymlinkPrefix data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Ino = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Phys = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.TargetLen = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	return nil
}

// Packed layout: 20 bytes (field-width sum verified at generation time).

// Size returns the on-disk size of JrnTrieAlloc.
func (s *JrnTrieAlloc) Size() int { return int(unsafe.Sizeof(JrnTrieAlloc{})) }

// MarshalBinary serializes JrnTrieAlloc to its little-endian on-disk representation.
func (s *JrnTrieAlloc) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Block); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.Op); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Reserved); pos += 4
	return data, nil
}

// UnmarshalBinary deserializes JrnTrieAlloc from its little-endian on-disk representation.
func (s *JrnTrieAlloc) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("JrnTrieAlloc data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Block = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Op = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Reserved = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	return nil
}

// Compile-time size assertion for JrnTrieAlloc.
var _ = [1]struct{}{}[unsafe.Sizeof(JrnTrieAlloc{}) - 16]

// Size returns the on-disk size of JrnXattrPrefix. Packed structs have
// unaligned on-disk fields that Go's struct alignment cannot represent, so
// this is the declared size, not unsafe.Sizeof (the field-width sum is
// verified at generation time).
func (s *JrnXattrPrefix) Size() int { return 20 }

// MarshalBinary serializes JrnXattrPrefix to its little-endian on-disk representation.
func (s *JrnXattrPrefix) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Ino); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.PhysBlk); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.UsedSize); pos += 4
	return data, nil
}

// UnmarshalBinary deserializes JrnXattrPrefix from its little-endian on-disk representation.
func (s *JrnXattrPrefix) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("JrnXattrPrefix data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Ino = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.PhysBlk = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.UsedSize = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	return nil
}

// Packed layout: 20 bytes (field-width sum verified at generation time).

// Size returns the on-disk size of RecordHeader.
func (s *RecordHeader) Size() int { return int(unsafe.Sizeof(RecordHeader{})) }

// MarshalBinary serializes RecordHeader to its little-endian on-disk representation.
func (s *RecordHeader) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint32(data[pos:], s.Type); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Flags); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.DataLen); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Checksum); pos += 4
	return data, nil
}

// UnmarshalBinary deserializes RecordHeader from its little-endian on-disk representation.
func (s *RecordHeader) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("RecordHeader data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Type = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Flags = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.DataLen = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Checksum = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	return nil
}

// Compile-time size assertion for RecordHeader.
var _ = [1]struct{}{}[unsafe.Sizeof(RecordHeader{}) - 16]

// Size returns the on-disk size of SuperblockLayout.
func (s *SuperblockLayout) Size() int { return int(unsafe.Sizeof(SuperblockLayout{})) }

// MarshalBinary serializes SuperblockLayout to its little-endian on-disk representation.
func (s *SuperblockLayout) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.Magic); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.MajorVer); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.MinorVer); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.PatchVer); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.TotalBlocks); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.DataBlocks); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.BlockSize); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.InodeSize); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.BlocksGrp); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.InodesGrp); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FSCreated); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FSLastMount); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FSLastChkpt); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FreeDataBlks); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FreeInodes); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.RootIno); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FeatCompat); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FeatROCompat); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.FeatIncompat); pos += 8
	copy(data[pos:], s.UUID[:]); pos += 16
	binary.LittleEndian.PutUint64(data[pos:], s.EATOffset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.EATBlocks); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.TrieRootBlock); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.TrieBlocksUsed); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.TrieNodePoolStart); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.TrieNodePoolSize); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.InodeBMOffset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.InodeBMBlocks); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.InodeTableOffset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.JournalOffset); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.JournalBlocks); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.CheckpointSeq); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.JournalLogStart); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.JournalLogEnd); pos += 8
	for i := 0; i < len(s.ReservedJournal); i++ {
		binary.LittleEndian.PutUint64(data[pos:], s.ReservedJournal[i]); pos += 8
	}
	copy(data[pos:], s.Label[:]); pos += 64
	copy(data[pos:], s.Reserved[:]); pos += 648
	return data, nil
}

// UnmarshalBinary deserializes SuperblockLayout from its little-endian on-disk representation.
func (s *SuperblockLayout) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("SuperblockLayout data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Magic = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.MajorVer = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.MinorVer = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.PatchVer = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.TotalBlocks = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.DataBlocks = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.BlockSize = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.InodeSize = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.BlocksGrp = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.InodesGrp = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FSCreated = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FSLastMount = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FSLastChkpt = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FreeDataBlks = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FreeInodes = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.RootIno = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FeatCompat = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FeatROCompat = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.FeatIncompat = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	copy(s.UUID[:], data[pos:pos+16]); pos += 16
	s.EATOffset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.EATBlocks = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.TrieRootBlock = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.TrieBlocksUsed = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.TrieNodePoolStart = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.TrieNodePoolSize = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.InodeBMOffset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.InodeBMBlocks = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.InodeTableOffset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.JournalOffset = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.JournalBlocks = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.CheckpointSeq = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.JournalLogStart = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.JournalLogEnd = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	for i := 0; i < len(s.ReservedJournal); i++ {
		s.ReservedJournal[i] = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	}
	copy(s.Label[:], data[pos:pos+64]); pos += 64
	copy(s.Reserved[:], data[pos:pos+648]); pos += 648
	return nil
}

// Compile-time size assertion for SuperblockLayout.
var _ = [1]struct{}{}[unsafe.Sizeof(SuperblockLayout{}) - 1024]

// Size returns the on-disk size of TriePage. Packed structs have
// unaligned on-disk fields that Go's struct alignment cannot represent, so
// this is the declared size, not unsafe.Sizeof (the field-width sum is
// verified at generation time).
func (s *TriePage) Size() int { return 20 }

// MarshalBinary serializes TriePage to its little-endian on-disk representation.
func (s *TriePage) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint32(data[pos:], s.Magic); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Version); pos += 4
	binary.LittleEndian.PutUint16(data[pos:], s.LiveCount); pos += 2
	binary.LittleEndian.PutUint16(data[pos:], s.FreeNameOff); pos += 2
	binary.LittleEndian.PutUint64(data[pos:], s.FreeSlots); pos += 8
	return data, nil
}

// UnmarshalBinary deserializes TriePage from its little-endian on-disk representation.
func (s *TriePage) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("TriePage data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Magic = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Version = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.LiveCount = binary.LittleEndian.Uint16(data[pos:]); pos += 2
	s.FreeNameOff = binary.LittleEndian.Uint16(data[pos:]); pos += 2
	s.FreeSlots = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	return nil
}

// Packed layout: 20 bytes (field-width sum verified at generation time).

// Size returns the on-disk size of TrieSlot. Packed structs have
// unaligned on-disk fields that Go's struct alignment cannot represent, so
// this is the declared size, not unsafe.Sizeof (the field-width sum is
// verified at generation time).
func (s *TrieSlot) Size() int { return 36 }

// MarshalBinary serializes TrieSlot to its little-endian on-disk representation.
func (s *TrieSlot) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint64(data[pos:], s.FirstChild); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.NextSibling); pos += 8
	binary.LittleEndian.PutUint64(data[pos:], s.Inode); pos += 8
	binary.LittleEndian.PutUint16(data[pos:], s.NameLen); pos += 2
	binary.LittleEndian.PutUint16(data[pos:], s.NameOffset); pos += 2
	data[pos] = s.Depth; pos += 1
	data[pos] = s.NodeType; pos += 1
	data[pos] = s.ByteVal; pos += 1
	data[pos] = s.FType; pos += 1
	binary.LittleEndian.PutUint16(data[pos:], s.Flags); pos += 2
	binary.LittleEndian.PutUint16(data[pos:], s.ChildCount); pos += 2
	return data, nil
}

// UnmarshalBinary deserializes TrieSlot from its little-endian on-disk representation.
func (s *TrieSlot) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("TrieSlot data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.FirstChild = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.NextSibling = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Inode = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.NameLen = binary.LittleEndian.Uint16(data[pos:]); pos += 2
	s.NameOffset = binary.LittleEndian.Uint16(data[pos:]); pos += 2
	s.Depth = data[pos]; pos += 1
	s.NodeType = data[pos]; pos += 1
	s.ByteVal = data[pos]; pos += 1
	s.FType = data[pos]; pos += 1
	s.Flags = binary.LittleEndian.Uint16(data[pos:]); pos += 2
	s.ChildCount = binary.LittleEndian.Uint16(data[pos:]); pos += 2
	return nil
}

// Packed layout: 36 bytes (field-width sum verified at generation time).

// Size returns the on-disk size of XattrEntry.
func (s *XattrEntry) Size() int { return int(unsafe.Sizeof(XattrEntry{})) }

// MarshalBinary serializes XattrEntry to its little-endian on-disk representation.
func (s *XattrEntry) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint16(data[pos:], s.NameLen); pos += 2
	binary.LittleEndian.PutUint16(data[pos:], s.ValueLen); pos += 2
	binary.LittleEndian.PutUint16(data[pos:], s.NameOffset); pos += 2
	binary.LittleEndian.PutUint16(data[pos:], s.ValueOffset); pos += 2
	return data, nil
}

// UnmarshalBinary deserializes XattrEntry from its little-endian on-disk representation.
func (s *XattrEntry) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("XattrEntry data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.NameLen = binary.LittleEndian.Uint16(data[pos:]); pos += 2
	s.ValueLen = binary.LittleEndian.Uint16(data[pos:]); pos += 2
	s.NameOffset = binary.LittleEndian.Uint16(data[pos:]); pos += 2
	s.ValueOffset = binary.LittleEndian.Uint16(data[pos:]); pos += 2
	return nil
}

// Compile-time size assertion for XattrEntry.
var _ = [1]struct{}{}[unsafe.Sizeof(XattrEntry{}) - 8]

// Size returns the on-disk size of XattrHeader.
func (s *XattrHeader) Size() int { return int(unsafe.Sizeof(XattrHeader{})) }

// MarshalBinary serializes XattrHeader to its little-endian on-disk representation.
func (s *XattrHeader) MarshalBinary() ([]byte, error) {
	data := make([]byte, s.Size())
	pos := 0
	binary.LittleEndian.PutUint32(data[pos:], s.Magic); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Version); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.UsedSize); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.EntryCount); pos += 4
	binary.LittleEndian.PutUint64(data[pos:], s.NextBlock); pos += 8
	binary.LittleEndian.PutUint32(data[pos:], s.Flags); pos += 4
	binary.LittleEndian.PutUint32(data[pos:], s.Reserved); pos += 4
	return data, nil
}

// UnmarshalBinary deserializes XattrHeader from its little-endian on-disk representation.
func (s *XattrHeader) UnmarshalBinary(data []byte) error {
	if len(data) < s.Size() {
		return fmt.Errorf("XattrHeader data too short: %d < %d", len(data), s.Size())
	}
	pos := 0
	s.Magic = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Version = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.UsedSize = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.EntryCount = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.NextBlock = binary.LittleEndian.Uint64(data[pos:]); pos += 8
	s.Flags = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	s.Reserved = binary.LittleEndian.Uint32(data[pos:]); pos += 4
	return nil
}

// Compile-time size assertion for XattrHeader.
var _ = [1]struct{}{}[unsafe.Sizeof(XattrHeader{}) - 32]

